# print('a', 'b', 'c', sep='*')
# print('d', 'e', 'f', sep='**', end='')
# print('g', 'h', 'i', sep='+', end='%')
# print('j', 'k', 'l', sep='-', end='\n')
# print('m', 'n', 'o', sep='/', end='!')
# print('p', 'q', 'r', sep='1', end='%')
# print('s', 't', 'u', sep='&', end='\n')
# print('v', 'w', 'x', sep='%')
# print('y', 'z', sep='/', end='!')
# ____________________________________________
# a = int(input())
# print(a)
# print(a+1)
# print(a+2)
# _____________________________________________
# a = int(input())
# b = int(input())
# print(3*(a+b)*(a+b)*(a+b)+275*b*b-127*a-41)
# _________________________________________________
#  a = int(input())
# print('Следующее за числом', a, 'число: ', a+1)
# print('Для числа', a, 'предыдущее число: ', a-1)
# ______________________________________________________
# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print((a+b+c+d)*3)
# _______________________________________________________
# a = int(input())
# b = int(input())
# print(a, "+", b, "=", a+b)
# print(a, "-", b, "=", a-b)
# print(a, "*", b, "=", a*b)
# _____________________________________________
# a1 = int(input())
# d = int(input())
# n = int(input())
# print(a1+d*(n-1))
# ____________________________________________
# x = int(input())
# print(x, 2*x, 3*x, 4*x, 5*x, sep="---")
# x = int(input())

# print(x, end="...")
# print(2*x, end="...")
# print(3*x, end="...")
# print(4*x, end="...")
# print(5*x)
# print("*******************")
# print("*                 *")
# print("*                 *")
# print("*******************")
# a = int(input())
# b = int(input())
# print('Квадрат суммы', a, 'и', b, "равен", ((a+b)**2))
# print('Сумма квадратов', a, 'и', b, "равен", (a**2+b**2))
# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a**b+c**d)
# n = int(input())
# print(n*100+(n+n)*10+(n+n+n))
